In [2]:
import numpy as np
import sys

In [7]:
price_list = [2000,14,56,3452,567]
price_array = np.array(price_list)

print(f"From list :{price_list}")
print(f"From array :{price_array}")
print(f"Shape : {price_array.shape}")

From list :[2000, 14, 56, 3452, 567]
From array :[2000   14   56 3452  567]
Shape : (5,)


In [10]:
price_list = [[2000,14,56,3452,567]]
price_array = np.array(price_list)
print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"Shape : {price_array.shape}")

From list : [[2000, 14, 56, 3452, 567]]
From array : [[2000   14   56 3452  567]]
Shape : (1, 5)


In [11]:
price_list = [[2000],[14],[56],[3452],[567]]
price_array = np.array(price_list)
print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"Shape : {price_array.shape}")

From list : [[2000], [14], [56], [3452], [567]]
From array : [[2000]
 [  14]
 [  56]
 [3452]
 [ 567]]
Shape : (5, 1)


##### Need to under stand the multidimension array 


### 2. Python List vs Numpy Array

#### 2.1 Memory

In [ ]:
size =  10000
python_list = list(range(size))
numpy_array = np.arange(size)

list_memory = sys.getsizeof(python_list)+sum(sys.getsizeof(x) for x in python_list)
array_memory = sys.getsizeof(numpy_array)

print(f"Python list memory : {list_memory}")
print(f"Numpy array memory : {array_memory}")

print(f"Times {list_memory/array_memory}")



Python list memory : 360056
Numpy array memory : 80112
Times 4.4944078290393445


### 3. Vectorization and Broadcasting

### 3.1 Vectorization

In [ ]:
a_list  = [1,2,3,4]
a_array = np.array([1,2,3,4])

print(f"a_list  * 3 : {a_list * 3}")
print(f"a_array * 3 : {a_array * 3}")

a_list  * 3 : [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
a_array * 2 : [ 3  6  9 12]


In [5]:
a1 = np.ones((6),dtype=int)

a = np.ones(6)

b = np.ones((6,1))
c = np.ones((1,6))

print(a1)

print(a)
print(b)
print(c)

[1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1.]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1. 1.]]
