In [1]:
import numpy as np
import sys

In [7]:
price_list = [2000,14,56,3452,567]
price_array = np.array(price_list)

print(f"From list :{price_list}")
print(f"From array :{price_array}")
print(f"Shape : {price_array.shape}")

From list :[2000, 14, 56, 3452, 567]
From array :[2000   14   56 3452  567]
Shape : (5,)


In [10]:
price_list = [[2000,14,56,3452,567]]
price_array = np.array(price_list)
print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"Shape : {price_array.shape}")

From list : [[2000, 14, 56, 3452, 567]]
From array : [[2000   14   56 3452  567]]
Shape : (1, 5)


In [11]:
price_list = [[2000],[14],[56],[3452],[567]]
price_array = np.array(price_list)
print(f"From list : {price_list}")
print(f"From array : {price_array}")
print(f"Shape : {price_array.shape}")

From list : [[2000], [14], [56], [3452], [567]]
From array : [[2000]
 [  14]
 [  56]
 [3452]
 [ 567]]
Shape : (5, 1)


##### Need to under stand the multidimension array 


### 2. Python List vs Numpy Array

#### 2.1 Memory

In [ ]:
size =  10000
python_list = list(range(size))
numpy_array = np.arange(size)

list_memory = sys.getsizeof(python_list)+sum(sys.getsizeof(x) for x in python_list)
array_memory = sys.getsizeof(numpy_array)

print(f"Python list memory : {list_memory}")
print(f"Numpy array memory : {array_memory}")

print(f"Times {list_memory/array_memory}")



Python list memory : 360056
Numpy array memory : 80112
Times 4.4944078290393445


### 3. Vectorization and Broadcasting

### 3.1 Vectorization

In [ ]:
a_list  = [1,2,3,4]
a_array = np.array([1,2,3,4])

print(f"a_list  * 3 : {a_list * 3}")
print(f"a_array * 3 : {a_array * 3}")

a_list  * 3 : [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
a_array * 2 : [ 3  6  9 12]


In [9]:
a1 = np.ones((6),dtype=int)

a = np.ones(6)

b = np.ones((6,1))
c = np.ones((1,6))

print(f"a1 : {a1}\n")

print(f"a : {a}\n")
print(f"b : {b}\n")
print(f"c : {c}\n")

a1 : [1 1 1 1 1 1]

a : [1. 1. 1. 1. 1. 1.]

b : [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

c : [[1. 1. 1. 1. 1. 1.]]



In [7]:
ab = a+b
ac = a+c
bc = b+c

print(ab)
print("")

print(ac)
print("")

print(bc)


[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]

[[2. 2. 2. 2. 2. 2.]]

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]


#### Application
3 Students

- Isuru (70,60,50,40)
- Asloof (99,100,98,97)
- Kavin (65,41,45,90)

4 Subject 

- Maths
- Science 
- History 
- Health

Weight

- 0.5
- 0.4
- 0.07
- 0.03







In [ ]:
marks_weight = np.array([0.5,0.4,0.07,0.03])

marks = np.array([
    [76,60,50,40],
    [99,100,98,97],
    [65,41,45,90]
])